# PyTorch Fundamentals

Let's quickly check to see if PyTorch is available and working with our GPU. Consider using [Google Colab](https://colab.research.google.com/) if all else fails.

In [69]:
import torch
x = torch.rand(5, 3)
print(x)

tensor([[0.8025, 0.5420, 0.9487],
        [0.7616, 0.2076, 0.6247],
        [0.9549, 0.6266, 0.9909],
        [0.4829, 0.9729, 0.2125],
        [0.2650, 0.8753, 0.6273]])


In [70]:
torch.cuda.is_available()

True

## Introduction to Tensors

Tensors are considered the building blocks of neural networks, and deep learning in general. Even though most references in PyTorch are to just '[tensors](https://pytorch.org/docs/stable/tensors.html)', there exists various kinds of tensors. All a tensor is in this context is "a multi-dimensional matrix containing elements of a single data type". We instantiate tensors using `torch.Tensor`.

In [53]:
import torch
import pandas as pd
import matplotlib as mpl
import numpy as np

### Scalars

$a$ - A tensor being comprised of a scalar simply means it is made of a real number and not a vector, and therefore exists in 0 dimensions. A dot, if you will.

```py
# Scalar - a real number rather than a vector
scalar = torch.Tensor(8)
```

### Vectors

$y$ - A vector is a pair of values that represent an arrow with a length and direction, with the arrows length being its magnitude and its direction being its orientation in what is called [Vector Space](https://www.youtube.com/watch?v=ozwodzD5bJM). A vector with only 1 pair of values is considered 1 dimensional, as it only represent 1 direction in Vector Space.

```py
# Vector - an object that has both a magnitude and a direction
vector = torch.Tensor([8,8])
```

### Matrices

$Q$ - A matrix is a set of numbers arranged in rows and columns to form a rectangular array and the size of this matrix is its size in element count in two dimensions.

```py
# Matrix - a 2 dimensional array of numbers
MATRIX = torch.Tensor([[8, 8],[9, 9]])
```

### Tensors

$X$ - "A PyTorch Tensor is basically the same as a numpy array: it does not know anything about deep learning or computational graphs or gradients, and is just a generic n-dimensional array to be used for arbitrary numeric computation." -- PyTorch's Documentation. In other words: A grid of values, all of the same type, and is indexed by a tuple of nonnegative integers.

```py
# Tensor - a 3 dimensional array of numbers
TENSOR = torch.Tensor([[[8, 8, 8],[9, 9, 9],[7, 7, 7]]])
```

### Random Tensors

It is unlikely that we will ever manually assign tensor values, simply becuase of the nature of self-learning algorithms and bias. It makes much more sense to use PyTorch's built in random function to create a tensor. Remember, we start with random values and then adjust those values as the model trains.

Creating random tensors in PyTorch is straightforward.

```py
randomTensor = torch.rand(1, 3, 4)
randomTensor
tensor([[[0.6703, 0.4746, 0.3914, 0.4547],
         [0.7721, 0.7192, 0.2338, 0.9072],
         [0.9905, 0.0131, 0.0025, 0.9264]]])
```

Our preprocessed input data can be represented easily by tensors. For instance, a colour image of 100 by 100 pixels would be split into Red, Green, and Blue channels and would correspond to three dimensions in our tensor represented as a: `colour_channel`, `height_channel`, and `width_channel`.

```py
# a vector consisting of 30,000 elements representing an RGB image of 100,100px
rgb_picture = torch.rand(3,100,100)
```

### Tensor Masking

If we were, for instance, required to produce a tensor that is all zeros, or all ones. We might employ what is called `maskin`. By multiplying our zero'd mask with another tensor, we can effectively mask ranges of ellements within our tensor.

```py
zmask = torch.zeros(5,5)
randTensor = randTensor * zmask
```

### Tensors Ranges

We can ask PyTorch to generate ranges with step-sizes and mask ranges with `torch.zeros_like()`

```py
one_to_ten_by_two = torch.arange(0,10,2)
torch.zeros_like(one_to_ten_by_two)

# the output should be tensor([0, 0, 0, 0, 0])
```

### Tensor Datatypes and Parameters

The default datatype in PyTorch is float32, in order to change the datatype, we can assign specific datatypes as a paramater option, along with which device it should run on and wheter gradients are tracked during the operation of the tensor.

```py
a_shiny_new_tensor = torch.Tensor([3.0, 2.0, 1.0],
                                    dtype=None,  # Datatype of the tensor
                                    device=None,  # Device our tensor is on
                                    requires_grad=False  # Whether or not to track gradients of this tensor
                                    )
```

### Tensor Manipulation (Operations)

Our neural network will make use of the following operations to manipulate our tensors in order to represent our dataset, this is where our inputs and channel weights are added to our baises during the feed forward portion of our neural network's learning process:

1. Addition
2. Subtraction
3. Scalar Multiplication (multiplication by a single value)
4. Matrix Multiplication (multiplication of matrices by matrices, [dot product](https://en.wikipedia.org/wiki/Dot_product))
5. Division

#### Addition


In [57]:
TENSOR = torch.tensor([1,2,2])
print(TENSOR)
print(TENSOR + 10)

tensor([1, 2, 2])
tensor([11, 12, 12])


#### Subtraction

In [58]:
TENSOR = torch.tensor([1,2,2])
print(TENSOR)
print(TENSOR - 10)

tensor([1, 2, 2])
tensor([-9, -8, -8])


#### Multiplication

In [65]:
TENSOR = torch.tensor([1,2,2])
print(TENSOR)
print(TENSOR * 10)

# also

TENSOR1 = torch.tensor([1,2,3])
TENSOR2 = torch.tensor([1,2,3])
print(TENSOR1 * TENSOR2)

tensor([1, 2, 2])
tensor([10, 20, 20])
tensor([1, 4, 9])


#### Matrix Multiplication

In [67]:
TENSOR1 = torch.tensor([1,2,3])
TENSOR2 = torch.tensor([1,2,3])
print(torch.matmul(TENSOR1,TENSOR2))

tensor(14)


#### Division

In [68]:
TENSOR = torch.tensor([1,2,2])
print(TENSOR)
print(TENSOR / 10)

tensor([1, 2, 2])
tensor([0.1000, 0.2000, 0.2000])
